%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

helpdlg({'','L I N E   D E T E C T I O N   U S I N G   H O U G H   T R A N S F O R M',...
      'Done by:',...
      '         R a f e e f     A b u g h a r b i e h',...
      '         K a r i n     A l t h o f f',...
      '         G h a s s a n     H a m a r n e h','September 1999'},...   
   'About');